### ISSUE TITLE
'AdbClient' does not contain a definition for 'Instance' version 2.3.22 - 2.3.14

### ISSUE THREAD

**Issue by 5p134n** [quamotion/madb#192] opened 2020-06-26 12:47 UTC
Hi

I'm newbie. Maybe I'm doing something wrong
But I get an error 'AdbClient' does not contain a definition for 'Instance' SharpAdbClient version 2.3.22 - 2.3.14 installed via Nuget.
http://prntscr.com/t6xojm

But everything works in the version 2.3.12.

**Comment by qmfrederik** [comment] 2020-06-26 14:35
This is a duplicate of #191. It's an intentional change - we've tried to remove all static methods/properties from the library.
It should nudge you to use dependency injection, but you're of course free to create your own static property if you so desire.

**Closed by qmfrederik** 2020-06-26 14:35 UTC
