### ISSUE TITLE
GetFrameBuffer CPU-Use

### ISSUE THREAD

**Issue by Viper2k4** [quamotion/madb#40] opened 2016-05-20 08:15 UTC
Hi,

it looks like there is a CPU-Use issue in this function.

But i think a sample is even more helpfull to reproduce:

```
var device = AdbClient.Instance.GetDevices().First();

while (true)
{
    var img = AdbClient.Instance.GetFrameBufferAsync(device, CancellationToken.None).Result;
    Thread.Sleep(100);
}
```

The CPU-Use from adb.exe is only 0-2%. But the GetFrameBufferAsync-function jumps to 30% (if VS dont lie). Donno what happend here :/

(i know it's a bit like #39 but i truly think the CPU-Use problem is not an adb-problem)

Greetings

*EDIT*

i think i found the problem. The `AdbSocket.Read` use a while loop which some times runs in idle and let the CPU-Use grow. A simple `Thread.Sleep(1);` reduce the CPU-Use down to < 10%. A `Thread.Sleep(10);` to < 5%.

Maybe there is a more efficient way to check for idle. But i'm relative sure that this is the problem.

Before:

![before](https://cloud.githubusercontent.com/assets/15054322/15422805/8837dc24-1e7a-11e6-98d8-e73a41a888a4.png)
(Sry for the german image)

After (1ms delay):

![after_1ms](https://cloud.githubusercontent.com/assets/15054322/15422817/966014f6-1e7a-11e6-935d-c3a64feea3ef.png)
(Sry for the german image)

*EDIT2*

Btw. `GetFrameBufferAsync` could also use `AdbSocket.ReadAsync` instand of the sync version. But the `AdbSocket.ReadAsync` is also missing the `Thread.Sleep(1);` or somthing more efficient^^

*EDIT3*

It does not even make a big different in result (run time of the function) if use Sleep(1) or Sleep(10). But CPU-Use also drops again 50%. So for me 10ms would be perfect.

But it would be perfect if the socked it self would block until there are no data to Receive.

*EDIT4*

Btw. an optimum would be if madb could deliver a stream of this:

http://stackoverflow.com/questions/26786926/android-screen-capture

I try it in ABD and its very very very fast.

**Comment by qmfrederik** [comment] 2016-06-02 22:27
@Viper2k4 , #43 provides some thoughts on how I think we can address this, feel free to have a look.
I think the `Sleep` statements mitigated the problem but did not really address the root cause, let me know what you think.

**Comment by qmfrederik** [comment] 2016-06-03 09:07
https://github.com/openstf/adbkit/issues/30 has some details how to use screenrecord to get H.264 streams

**Comment by Viper2k4** [comment] 2016-06-03 09:42
That's exact what i mean. I try it and it worked well on ADB it self. There is only a Stream if there is a change on the display. So if the display is off there is less traffic (because all black and no changes).

I think it could be a bit faster as repeatedly request the framebuffer, like i do actual.

There are even some more hidden commands and options:

https://android.googlesource.com/platform/frameworks/av/+/master/cmds/screenrecord/screenrecord.cpp

**Comment by qmfrederik** [comment] 2016-06-03 12:41
Cool, thanks!

I'll investigate when I have the time & get back to you. Thanks for the links to screenrecord; I was indeed wondering about the 3-minute timeout, so let's see if we can work around that :-). If you find out new stuff feel free to share it here!

**Comment by Viper2k4** [comment] 2016-06-28 10:33
Should we close this or should we let it open as reminder for screenrecord?

**Comment by qmfrederik** [comment] 2016-06-30 14:07
Yeah, I wanted to keep it open for screenrecord but it confused me every time, so I've created #55 and will close this one.

Thanks!

**Closed by qmfrederik** 2016-06-30 14:07 UTC
